name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install pipenv
      - run: pipenv install --dev --ignore-pipfile
      - run: pipenv run flake8 .
      - run: pipenv run black --line-length=120 --check .
      - run: pipenv run isort --check --line-length 120 --profile black .
      - run: |
          mkdir -p $HOME/.local/bin
          wget https://static.snyk.io/cli/latest/snyk-linux -O $HOME/.local/bin/snyk
          chmod +x $HOME/.local/bin/snyk
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: snyk test --org=devops-0yx --project-name=${{ github.event.repository.name }}
      - run: snyk code test --org=devops-0yx --project-name=${{ github.event.repository.name }}
  build_release:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: build_release
    environment: Development
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=date::$(date +'%FT%H%M%SZ')"
        id: date
      - uses: docker/login-action@v1
        with:
          registry: binkcore.azurecr.io
          username: binkcore
          password: ${{ secrets.ACR_BINKCORE_PASSWORD }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            binkcore.azurecr.io/${{ github.event.repository.name }}:${{ steps.date.outputs.date }}
            binkcore.azurecr.io/${{ github.event.repository.name }}:latest
